source("functions_setup/mlab-setup.r")

#####################
# Joining with Congressional Districts 
#		Since the US Census API does not yet support geometries for Congressional 
#		Districts, instead, we'll use an imported shapefile to obtain the geometries.
# 
# Import shapefile as an sf dataframe
cd_115<- st_read(dsn="geofiles/us_legislative_districts", 
	layer="cb_2017_us_cd115_500k", quiet=TRUE)

# Filter to the state we're interested in
MN_cd_115 <- filter(cd_115, STATEFP == "27")

#####################
# Get and prepare M-Lab Download speed data
#####################
with_config(config(http_version = 2), { 
	MN_2018_download_initial <- pull_mm_ndt("2018-01-01", "2018-07-31", sql_download, 
		"'Minnesota'","MN") })

## A little data cleaning to filter data any rows that might not be in the correct country
MN_2018_download <- filter(MN_2018_download_initial, country_code == "US")

## Convert to a simple features dataframe
coordinates(MN_2018_download) <- c("client_lon", "client_lat")
MN2018_down_sf <- st_as_sf(MN_2018_download)

## Set the layer CRSs to be the same
st_crs(MN2018_down_sf) <- st_crs(MN_cd_115)

## Do spatial join to add congressional district to speed test rows
MN_2018_down_cd115 <- bind_cols( 
  MN_2018_download@data,
  MN_cd_115[as.numeric(st_within(MN2018_down_sf, MN_cd_115)),]
)

#####################
# Compute Download medians by district
#####################
# First summary of median download speed to reduce sample bias
#   This first step produces download speed medians by district, day, and client_ip, reducing potential sample bias from 
#   multiple tests from the same ip addresses over time
MN_2018_DL_IP_day_district <- MN_2018_down_cd115 %>%
  group_by(CD115FP,format(as.Date(log_time), "%Y-%m-%d"),client_ip) %>%
  summarize(median_dl = median(download_speed_Mbps))

## Rename the 'day' column generated by the transform of log_time in the previous DF
names(MN_2018_DL_IP_day_district)[2] = "day"

## Second and final summary of median download speed by district 
##   This second summarization groups the previously calculated medians by district, day, and client_ip to simply medians by district
MN_2018_download_median_cd115 <- MN_2018_DL_IP_day_district %>%
  group_by(CD115FP) %>%
  summarize(median_download_Mbps = median(median_dl))

## Prepare for mapping
MN_districts <- readOGR(dsn="examples/geofiles/MN_legis_dists", layer="MN_cd115",
	stringsAsFactors = FALSE)
centroids.MN_districts <- as.data.frame(coordinates(MN_districts))
MN_2018_DL_median_ip_day_district_withCentroids <- data.frame(MN_2018_download_median_cd115, centroids.MN_districts)

## Rejoin the geometry field so we can map median speeds by district
MN_2018_DL_median_ip_day_district_map_centers <- left_join(MN_2018_download_median_cd115, 
                                                           MN_2018_DL_median_ip_day_district_withCentroids, by=c("CD115FP"))
MN_2018_DL_median_ip_day_district_map_final <- left_join(MN_2018_DL_median_ip_day_district_map_centers, 
                                                         MN_cd_115, by=c("CD115FP"))
names(MN_2018_DL_median_ip_day_district_map_final)[4] = "longitude"
names(MN_2018_DL_median_ip_day_district_map_final)[5] = "latitude"
names(MN_2018_DL_median_ip_day_district_map_final)[2] = "median_download_mbps"

#####################
# Create some visualizations
#####################

## Make a map with the ggplot package
MN_2018_median_down_cd115_plot <- MN_2018_DL_median_ip_day_district_map_final %>%
  ggplot(aes(fill=median_download_mbps),color=median_download_mbps) + 
  guides(fill=guide_legend(title="Median Download Speed (Mbps)")) + 
  theme_bw() +
  geom_sf() +
  geom_label_repel(aes(x=longitude, y=latitude, label=CD115FP), color="white", fill="darkgrey") +
  theme(panel.background = element_rect(fill= NA), panel.grid = element_blank(), panel.border = element_blank(),
        panel.grid.major = element_line(colour = "white"), panel.grid.minor = element_line(colour = "white"), 
        axis.text = element_blank(), axis.ticks = element_blank() )

## Make a bar chart by district
ggplot(MN_2018_DL_median_ip_day_district_map_final,aes(CD115FP, median_download_mbps, fill=median_download_mbps)) +
  guides(fill=guide_legend(title="Median Download Speed (Mbps)")) + 
  theme_bw() +
  geom_col() + 
  theme(panel.background = element_rect(fill= NA), panel.grid = element_blank(), panel.border = element_blank(),
        panel.grid.major = element_line(colour = "white"), panel.grid.minor = element_line(colour = "white"))+
  ggtitle("M-Lab Median Download Speeds by Congressional District, 2018 Q1-2") +
  xlab("Minnesota Congressional District") + ylab("Median Download Speed (Mbps)") +
  geom_text(aes(label=round(median_download_mbps,2)), vjust=1.5, color="white")

#####################
# Compute Download Speed by District and City
#####################
MN_2018_DL_IP_day_district_city <- MN_2018_down_cd115 %>%
  group_by(CD115FP,format(as.Date(log_time), "%Y-%m-%d"),client_ip,city) %>%
  summarize(median_dl = median(download_speed_Mbps))

names(MN_2018_DL_IP_day_district_city)[2] = "day"

MN_2018_download_median_cd115_city <- MN_2018_DL_IP_day_district_city %>%
  group_by(CD115FP,city) %>%
  summarize(median_download_Mbps = median(median_dl))

MN_3_DL_city <- filter(MN_2018_download_median_cd115_city, CD115FP == "03")

## Create a bar chart by city
ggplot(MN_3_DL_city,aes(reorder(city, -median_download_Mbps), median_download_Mbps, fill=median_download_Mbps)) +
  guides(fill=guide_legend(title="Median Download Speed (Mbps)")) + 
  theme_bw() +
  geom_col() + 
  theme(panel.background = element_rect(fill= NA), panel.grid = element_blank(), panel.border = element_blank(),
        panel.grid.major = element_line(colour = "white"), panel.grid.minor = element_line(colour = "white"))+
  ggtitle("M-Lab Median Download Speeds by City, MN 3, 2018 Q1-2") +
  xlab("City") + ylab("Median Download Speed (Mbps)") +
  geom_text(aes(label=round(median_download_Mbps,2)), hjust=1, color="white") +
  coord_flip()

#####################
# Get and prepare M-Lab Upload speed data
#####################
with_config(config(http_version = 2), { 
  MN_2018_upload_initial <- pull_mm_ndt("2018-01-01", "2018-07-31", sql_upload, 
  	"'Minnesota'","MN")})

MN_2018_upload <- filter(MN_2018_upload_initial, country_code == "US")
coordinates(MN_2018_upload) <- c("client_lon", "client_lat")

MN2018_up_sf <- st_as_sf(MN_2018_upload)

st_crs(MN2018_up_sf) <- st_crs(MN_cd_115)

MN_2018_up_cd115 <- bind_cols( 
  MN_2018_upload@data,
  MN_cd_115[as.numeric(st_within(MN2018_up_sf, MN_cd_115)),]
)

MN_2018_UL_IP_day_district <- MN_2018_up_cd115 %>%
  group_by(CD115FP,format(as.Date(log_time), "%Y-%m-%d"),client_ip) %>%
  summarize(median_ul = median(upload_speed_Mbps))

names(MN_2018_UL_IP_day_district)[2] = "day"

MN_2018_upload_median_cd115 <- MN_2018_UL_IP_day_district %>%
  group_by(CD115FP) %>%
  summarize(median_upload_Mbps = median(median_ul))

MN_2018_UL_median_ip_day_district <- left_join(MN_2018_upload_median_cd115, MN_cd_115, by=c("CD115FP"))

MN_districts <- readOGR(dsn="examples/geofiles/MN_legis_dists", layer="MN_cd115",stringsAsFactors = FALSE)
centroids.MN_districts <- as.data.frame(coordinates(MN_districts))

MN_2018_UL_median_ip_day_district_withCentroids <- data.frame(MN_2018_upload_median_cd115, centroids.MN_districts)

MN_2018_UL_median_ip_day_district_map_centers <- left_join(MN_2018_upload_median_cd115, 
                                                           MN_2018_UL_median_ip_day_district_withCentroids, by=c("CD115FP"))
MN_2018_UL_median_ip_day_district_map_final <- left_join(MN_2018_UL_median_ip_day_district_map_centers, 
                                                         MN_cd_115, by=c("CD115FP"))
names(MN_2018_UL_median_ip_day_district_map_final)[4] = "longitude"
names(MN_2018_UL_median_ip_day_district_map_final)[5] = "latitude"
names(MN_2018_UL_median_ip_day_district_map_final)[2] = "median_upload_mbps"


MN_2018_median_up_cd115_plot <- MN_2018_UL_median_ip_day_district_map_final %>%
  ggplot(aes(fill=median_upload_mbps),color=median_upload_mbps) + 
  guides(fill=guide_legend(title="Median Upload Speed (Mbps)")) + 
  theme_bw() +
  geom_sf() +
  geom_label_repel(aes(x=longitude, y=latitude, label=CD115FP), color="white", fill="darkgrey") +
  theme(panel.background = element_rect(fill= NA), panel.grid = element_blank(), panel.border = element_blank(),
        panel.grid.major = element_line(colour = "white"), panel.grid.minor = element_line(colour = "white"), 
        axis.text = element_blank(), axis.ticks = element_blank() )

ggplot(MN_2018_UL_median_ip_day_district_map_final,aes(CD115FP, median_upload_mbps, fill=median_upload_mbps)) +
  guides(fill=guide_legend(title="Median Upload Speed (Mbps)")) + 
  theme_bw() +
  geom_col() + 
  theme(panel.background = element_rect(fill= NA), panel.grid = element_blank(), panel.border = element_blank(),
        panel.grid.major = element_line(colour = "white"), panel.grid.minor = element_line(colour = "white"))+
  ggtitle("M-Lab Median Upload Speeds by Congressional District, 2018 Q1-2") +
  xlab("Minnesota Congressional District") + ylab("Median Upload Speed (Mbps)") #+

#####################
# Compute Upload Speed by District and City
#####################
MN_2018_UL_IP_day_district_city <- MN_2018_up_cd115 %>%
  group_by(CD115FP,format(as.Date(log_time), "%Y-%m-%d"),client_ip,city) %>%
  summarize(median_ul = median(upload_speed_Mbps))

names(MN_2018_UL_IP_day_district_city)[2] = "day"

MN_2018_upload_median_cd115_city <- MN_2018_UL_IP_day_district_city %>%
  group_by(CD115FP,city) %>%
  summarize(median_upload_Mbps = median(median_ul))

MN_3_UL_city <- filter(MN_2018_upload_median_cd115_city, CD115FP == "03")

ggplot(MN_3_UL_city,aes(reorder(city, -median_upload_Mbps), median_upload_Mbps, fill=median_upload_Mbps)) +
  guides(fill=guide_legend(title="Median Upload Speed (Mbps)")) + 
  theme_bw() +
  geom_col() + 
  theme(panel.background = element_rect(fill= NA), panel.grid = element_blank(), panel.border = element_blank(),
        panel.grid.major = element_line(colour = "white"), panel.grid.minor = element_line(colour = "white"))+
  ggtitle("M-Lab Median Upload Speeds by City, MN 3, 2018 Q1-2") +
  xlab("City") + ylab("Median Upload Speed (Mbps)") +
  geom_text(aes(label=round(median_upload_Mbps,6)), hjust=1.2, color="white") +
  coord_flip()
