library(bigrquery)
library(zipcode)
library(tidyverse)
library(ggplot2)
library(rgdal)
library(rgeos)
library(maptools)
library(viridis)
library(lubridate)
library(RColorBrewer)
library(reshape2)
library(tidycensus)
library(sp)
library(sf)
library(tigris)
library(rmapshaper)

# us_leg_dist_projection<- CRS("+proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs")
#https://www.nceas.ucsb.edu/scicomp/usecases/point-in-polygon

# Install your census api key for tidycensus
#census_api_key("xxxxxxxxxxxxxxxxxxxxxxx", install=TRUE)

#code to get all of the geom files for a country (or large region defined by totalpop_sf) in one sf object
us <- unique(fips_codes$state)[1:51]

totalpop_sf <- reduce(
  map(us, function(x) {
    # get_acs does not yet support congr distr geometry
    #    get_acs(geography = "congressional districts", variables = "B01003_001", 
    get_acs(geography = "tract", variables = "B01003_001", 
            state = x, geometry = TRUE)
  }), 
  rbind
)

# Import shapefile as and sf dataframe
cd_115<- st_read(dsn="examples/geofiles/us_legislative_districts", layer="cb_2017_us_cd115_500k", quiet=TRUE)

# Filter to the state we're interested in
MN_cd_115 <- filter(cd_115, STATEFP == "27")

# Convert to an simple features dataframe
coordinates(MN_2018_download) <- c("client_lon", "client_lat")
MN2018_down_sf <- st_as_sf(MN_2018_download)

coordinates(MN_2018_upload) <- c("client_lon", "client_lat")
MN2018_up_sf <- st_as_sf(MN_2018_upload)

# Set the layer CRSs to be the same
st_crs(MN2018_down_sf) <- st_crs(MN_cd_115)
st_crs(MN2018_up_sf) <- st_crs(MN_cd_115)

# do spatial join to add congressional district to speed test rows
MN_2018_down_cd115 <- bind_cols( 
  MN_2018_download@data,
  MN_cd_115[as.numeric(st_within(MN2018_down_sf, MN_cd_115)),]
)
MN_2018_up_cd115 <- bind_cols( 
  MN_2018_upload@data,
  MN_cd_115[as.numeric(st_within(MN2018_up_sf, MN_cd_115)),]
)

# First summary of median download speed to reduce sample bias
#   This first step produces download speed medians by district, day, and client_ip, reducing potential sample bias from 
#   multiple tests from the same ip addresses over time
MN_2018_DL_IP_day_district <- MN_2018_down_cd115 %>%
  group_by(CD115FP,format(as.Date(log_time), "%Y-%m-%d"),client_ip) %>%
  summarize(median_dl = median(download_speed_Mbps))

MN_2018_UL_IP_day_district <- MN_2018_up_cd115 %>%
  group_by(CD115FP,format(as.Date(log_time), "%Y-%m-%d"),client_ip) %>%
  summarize(median_ul = median(upload_speed_Mbps))

# Rename the 'day' column generated by the transform of log_time in the previous DF
names(MN_2018_DL_IP_day_district)[2] = "day"
names(MN_2018_UL_IP_day_district)[2] = "day"

# Second and final summary of median download speed by district 
#   This second summarization groups the previously calculated medians by district, day, and client_ip to simply medians by district
MN_2018_download_median_cd115 <- MN_2018_DL_IP_day_district %>%
  group_by(CD115FP) %>%
  summarize(median_download_Mbps = median(median_dl))

MN_2018_upload_median_cd115 <- MN_2018_UL_IP_day_district %>%
  group_by(CD115FP) %>%
  summarize(median_upload_Mbps = median(median_ul))

# Rejoin the geometry field so we can map median speeds by district
MN_2018_DL_median_ip_day_district <- left_join(MN_2018_download_median_cd115, MN_cd_115, by=c("CD115FP"))
MN_2018_UL_median_ip_day_district <- left_join(MN_2018_upload_median_cd115, MN_cd_115, by=c("CD115FP"))

# Do the mapping with ggplot
MN_2018_median_down_cd115_plot <- MN_2018_DL_median_ip_day_district %>%
  ggplot(aes(fill=median_download_Mbps),color=median_download_Mbps) + 
  guides(fill=guide_legend(title="Median Download Speed (Mbps)")) + 
  theme_bw() +
  theme(panel.background = element_rect(fill= NA), panel.grid = element_blank(), panel.border = element_blank(),
        panel.grid.major = element_line(colour = "white"), panel.grid.minor = element_line(colour = "white"), 
        axis.text = element_blank(), axis.ticks = element_blank() ) + 
  geom_sf() +
  geom_text(centroids.MNdist, label=id, x = "lon", y = "lat")

MN_2018_median_up_cd115_plot <- MN_2018_UL_median_ip_day_district %>%
  ggplot(aes(fill=median_upload_Mbps),color=median_upload_Mbps) + geom_sf()

districts <- readOGR(dsn="examples/geofiles/us_legislative_districts", layer="cb_2017_us_cd115_500k",stringsAsFactors = FALSE)
MN_districts <- districts[districts$STATEFP=="27",]
idList <- MN_districts@data$CD115FP
centroids.districts <- as.data.frame(coordinates(MN_districts))
centroids.MNdist <- as.data.frame(coordinates(MN_districts), MN_districts@data$CD115FP)

test.df <- data.frame(id=idList, centroids.districts)

geom_col(mapping = NULL, data = NULL, position = "stack", ...,
         width = NULL, na.rm = FALSE, show.legend = NA, inherit.aes = TRUE)
